### ISSUE TITLE
Add an option to just clean bin/obj from Solution

### ISSUE THREAD

**Issue by TimSirmovics** [conwid/VSCleanBin#1]
I only want to clean the bin/obj folders, not the packages folder, for the whole solution.

Currently the only way I can see to do this is to seperately do it for each project?

**Comment by conwid** [comment]
Correct.
I might have some free time this weekend to implement this - stay tuned ;)

**Comment by conwid** [comment]
Done. Hopefully I didn't screw up the publish, it's pretty late here :)

**Comment by TimSirmovics** [comment]
Thanks!
