### ISSUE TITLE
Delete Bin and Obj for Solution

### ISSUE THREAD

**Issue by mah-dc** [conwid/VSCleanBin#2]
![image](https://user-images.githubusercontent.com/55651782/65411078-3e5fd900-ddec-11e9-9fa7-3068154349ef.png)

If the project is inside a solution folder, I'm unable to clean the solution.

**Comment by lothargrieb** [comment]
Is this project dead? for large solutions with many folders this bug is a showstopper!

**Comment by conwid** [comment]
Well, I wouldn't say dead, but I'm not sure when I'll have the time to address the issue.
